baseURL = "https://kira-96.github.io/"
defaultContentLanguage = "zh"
languageCode = "zh"
title = "kira's åšå®¢"
author = "kira"
copyright = "Â© 2019-2023 [kira](/) &#183;"

theme = "PaperMod"

enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false
pygmentsUseClasses = true
# paginate = 5

[menu]
  [[menu.main]]
  name = "ä¸»é¡µ"
  url = "/"
  weight = 1
  [[menu.main]]
  name = "ç¬”è®°"
  url = "/notes/"
  weight = 2

[params]
  description = "kira's blog"
  favicon = "favicon.ico"
  lazyImage = true
  defaultTheme = "auto" # dark, light
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

# home-info mode
[params.homeInfoParams]
  Title = "kiraâœ¨åšå®¢ğŸ"
  Content = "æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ğŸ‰"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/kira-96/"
[[params.socialIcons]]
  name = "Rss"
  url = "index.xml"

[params.cover]
  hidden = true # hide everywhere but not in structured data
  hiddenInList = true # hide on list pages and home
  hiddenInSingle = true # hide on single page

[params.editPost]
  URL = "https://github.com/kira-96/kira-96.github.io/tree/main/content/posts/"
  Text = "ç¼–è¾‘" # edit text
  appendFilePath = false # to append file path to Edit link

[params.assets]
  # disableHLJS = true # to disable highlight.js
  # disableFingerprinting = true
  favicon = "https://cdn.jsdelivr.net/gh/kira-96/kira-96.github.io@gh-pages/favicon.ico"
  favicon16x16 = "https://cdn.jsdelivr.net/gh/kira-96/kira-96.github.io@gh-pages/favicon-16x16.png"
  favicon32x32 = "https://cdn.jsdelivr.net/gh/kira-96/kira-96.github.io@gh-pages/favicon-32x32.png"
  apple_touch_icon = "https://cdn.jsdelivr.net/gh/kira-96/kira-96.github.io@gh-pages/icons/apple-icon-180x180.png"
  safari_pinned_tab = "https://cdn.jsdelivr.net/gh/kira-96/kira-96.github.io@gh-pages/icons/apple-icon-76x76.png"
  theme_color = "#2e2e33"
  msapplication_TileColor = "#2e2e33"

# profile-mode
[params.profileMode]
  enabled = false # needs to be explicitly set
  title = "kira's åšå®¢"
  subtitle = "æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢"
  imageUrl = "https://cdn.jsdelivr.net/gh/kira-96/kira-96.github.io@gh-pages/icons/apple-icon-120x120.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = ""
  [[params.profileMode.buttons]]
  name = "ä¸»é¡µ"
  url = "posts"
  [[params.profileMode.buttons]]
  name = "ç¬”è®°"
  url = "notes"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4
